Repository Romanitho/Winget-AutoUpdate, pull requests merged in 2022-04, with the labels that each got.

#35 Add uninstall parameter
  Winget-AutoUpdate-Install.ps1
  uninstall.bat
Labels: enhancement

#40 Fix multiple Winget version cases
  Winget-AutoUpdate/config/about.xml
  Winget-AutoUpdate/functions/Get-WingetOutdatedApps.ps1
Labels: bug

#49 Add check for visual 2022
  Winget-AutoUpdate-Install.ps1
Labels: bug, enhancement

#51 Add nl locale
  Winget-AutoUpdate/locale/nl.xml
Labels: enhancement

#58 Added ES .xml translation
  Winget-AutoUpdate/locale/es.xml
Labels: enhancement

#56 Add winget install check
  Winget-AutoUpdate-Install.ps1
Labels: enhancement

#63 Added Notification Level Feature
  README.md
  Winget-AutoUpdate-Install.ps1
  Winget-AutoUpdate/config/about.xml
  Winget-AutoUpdate/functions/Get-NotifLocale.ps1
  Winget-AutoUpdate/functions/Get-WAUConfig.ps1
  Winget-AutoUpdate/functions/Start-NotifTask.ps1
  Winget-AutoUpdate/winget-upgrade.ps1
  install.bat
  uninstall.bat
Labels: enhancement

#67 Added Update frequency option
  README.md
  Winget-AutoUpdate-Install.ps1
  install.bat
Labels: enhancement
